<a href="https://colab.research.google.com/github/KengoTobita/libarts/blob/master/Pytorch_startup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorchの基本
Deep Learningの実装では多くの場合フレームワークを使用します。<br>
メジャーなフレームワークとして、KerasやTensorflowなどがありますが、<br>
本講座ではPytorchを使用していきます。<br>
<br>
PytorchはDLフレームワークとしては後発のものですが、<br>
他のフームワークと比べ複雑なモデルの構築に向いているため、近年人気が伸びています。<br>
KerasのSequentialモデルと比較して記述が複雑ではありますが、慣れてしまえば簡単です。<br>

# Pytorchのインストール
Pytorchは一般的なPythonライブラリと同様にpipでインストールすることが可能です。<br>
(環境によっては`pip3`だったり`pip`だったりするので確認を……)

In [0]:
!pip install torch
# pip install torch==1.0.0

     |████████████████████████████████| 753.4 MB 4.6 kB/s eta 0:00:011     |████████████▎                   | 289.3 MB 7.1 MB/s eta 0:01:06     |████████████████████▍           | 479.5 MB 9.8 MB/s eta 0:00:28     |█████████████████████           | 492.9 MB 7.1 MB/s eta 0:00:37     |██████████████████████████▏     | 615.0 MB 11.8 MB/s eta 0:00:12     |████████████████████████████▏   | 662.2 MB 7.9 MB/s eta 0:00:12     |████████████████████████████▏   | 663.5 MB 7.9 MB/s eta 0:00:12     |█████████████████████████████▏  | 687.9 MB 10.2 MB/s eta 0:00:07     |█████████████████████████████▍  | 691.0 MB 10.2 MB/s eta 0:00:07


In [0]:
!pip install torchvision
# pip install torchvision==0.2.2.post3

     |████████████████████████████████| 4.0 MB 2.2 MB/s eta 0:00:01


*** 
# Pytorchを使用してみよう
PytorchとNumpyの使用法は非常に似ています。<br>
(具体的にはtorch.Tensorとnumpy)<br>
ちょっと比べて遊んでみましょう。

In [0]:
import numpy as np

np.random.rand(5,3)

array([[0.37041896, 0.29177649, 0.44787035],
       [0.80256833, 0.85847219, 0.73132679],
       [0.39655734, 0.81532736, 0.78306572],
       [0.77681928, 0.57130169, 0.23434097],
       [0.68645574, 0.20437518, 0.71684916]])

In [0]:
import torch

import torchvision

torch.rand(5,3)

tensor([[0.8028, 0.3739, 0.9922],
        [0.7415, 0.6478, 0.4500],
        [0.1866, 0.3018, 0.2092],
        [0.7852, 0.8373, 0.6822],
        [0.9255, 0.6630, 0.6017]])

ゼロの生成


In [0]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [0]:
torch.tensor([5.5,3])

tensor([5.5000, 3.0000])

1のテンソル

In [0]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
torch.ones(5, 3, dtype=torch.double)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [0]:
torch.randn_like(x, dtype=torch.float)

tensor([[-0.6695, -1.2559, -1.0618],
        [-0.3863,  0.5426,  0.5391],
        [ 0.2109,  0.4228, -0.0670],
        [-1.6574,  1.2373, -0.5410],
        [ 1.2556,  0.0421,  1.1801]])

***
# 3.2 Neural Networkの実装
Pytorchの公式チュートリアルでは「Getting Started」として沢山のコンテンツが公開されています。<br>
今回は左上の「Deep Learning with Pytorch: A 60 Minute Blitz」を勉強します。<br>

## Autograd(自動微分)について

In [0]:
import torch 

# requires_gradがTrueだと自動微分
x = torch.ones(2,2, requires_grad=True)

print(x)
print(type(x))

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
<class 'torch.Tensor'>


type関数でxを見ると、`<class 'torch.Tensor'>`が出力されます。<br>
これはxが"Tensor"クラスのインスタンスであることを表しています。<br>
また、x定義時に`requires_grad`を`True`にしていることも確認しておいてください。

In [0]:
y = x+2

print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


`x`を入力として$y=x+2$を生成する`y`は属性`grad_fm`を持っています。<br>
これは`y`が演算の結果として生成されたためだとされています。<br>
さらに`y`に演算を行い`z`を生成します。

In [0]:
z = y*y*3 
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


上記のように$y\times y \times 3$という演算を行いました。<br>
`z`は`y`は3なので$y^3$で27です。<br>
そのため`z.mean()`で平均をとっても27です。

In [0]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


値はすべて4.5になっています。<br>
$((x+2)^2)'=6(x+2)$において$x＝1$にすると18ですが、<br>
最後に`z.mean()`で平均しているので値が4.5になっています。<br>

# 3.2 Neural Networkの実装

1. 学習可能なネットワークを定義する。
1. 入力データセットに関して繰り返し処理を行う。
1. ネットワークにおいて入力を計算する
1. 出力結果がどのくらい正解と異なっているか計算する
1. ネットワークのパラメータに対し誤差逆伝播を実行する。
1. $weight = weight - learning rate \times gradient$のような感じで重みをアップデート

# 3.2.1 Difine Network

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


ここでは各パラメータの確認をしています<br>
`net.parameters()`でパラメータの確認をすることが可能です。

In [0]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1

10
torch.Size([6, 1, 3, 3])


## 3.2.2 Loss function
ここでは損失関数を定義します。
今回は平均二乗誤差を使用します。

In [0]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(0.7788, grad_fn=<MseLossBackward>)


In [0]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([-0.0061, -0.0130, -0.0082, -0.0023,  0.0020,  0.0133])


### 3.2.4~3.2.5 BackDrop & Update the Weights 

In [0]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)
    
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()  

***